-- ТЗ 08: раздел «Радар» — разведка по рилсам конкурентов (docs/specs/08-radar.md).
-- Пять своих таблиц с префиксом radar_, ни одну существующую таблицу не трогает.
-- id рилса — shortcode Instagram (как в reels.shortcode), но таблицы раздельные:
-- у Радара своя модель данных (просмотры/метрики из Apify, разбор Gemini).

-- Конкуренты и их подписчики
create table if not exists public.radar_competitors (
  username              text primary key,
  followers             integer,
  followers_updated_at  timestamptz,
  added_at              timestamptz not null default now()
);

-- Прогоны Apify: сбор рилсов (kind=reels) и обновление подписчиков (kind=followers).
-- Запуск асинхронный: API стартует актор, статус доезжает при опросе GET /api/radar/scrape/{id}.
create table if not exists public.radar_scrape_runs (
  id                bigint generated by default as identity primary key,
  kind              text not null default 'reels' check (kind in ('reels', 'followers')),
  usernames         text[] not null default '{}',
  period_months     integer,
  status            text not null default 'pending' check (status in ('pending', 'running', 'done', 'error')),
  apify_run_id      text,
  apify_dataset_id  text,
  apify_token_ref   text,          -- хэш токена, которым запущен прогон (опрос — только тем же аккаунтом); сам токен не хранится
  results_count     integer,
  cost_estimate_usd numeric(10, 4),
  error             text,
  created_at        timestamptz not null default now(),
  finished_at       timestamptz
);

create index if not exists idx_radar_scrape_runs_created on public.radar_scrape_runs (created_at desc);

-- Рилсы конкурентов (метаданные из Apify, без видео)
create table if not exists public.radar_reels (
  id             text primary key,                -- shortcode
  username       text not null,
  url            text,
  caption        text,
  hashtags       jsonb not null default '[]'::jsonb,
  music          text,
  views          bigint,
  likes          integer,
  comments       integer,
  duration_sec   real,
  posted_at      timestamptz,
  video_url      text,                             -- подписанная ссылка CDN, живёт до параметра oe
  scrape_run_id  bigint references public.radar_scrape_runs(id) on delete set null,
  updated_at     timestamptz not null default now()
);

create index if not exists idx_radar_reels_username on public.radar_reels (username);
create index if not exists idx_radar_reels_views    on public.radar_reels (views desc);

-- Результат разбора рилса: расшифровка и видеоанализ (оба делает Gemini)
create table if not exists public.radar_analyses (
  reel_id              text primary key references public.radar_reels(id) on delete cascade,
  mode                 text not null check (mode in ('t', 'v', 'tv')),
  status               text not null default 'queued'
                       check (status in ('queued', 'downloading', 'analyzing', 'rate_limited', 'done', 'error', 'cancelled')),
  transcript_segments  jsonb,                     -- [{start, end, text}]
  transcript_engine    text,
  transcript_language  text,
  visual_timeline      jsonb,                     -- [{t, text}]
  hook                 text,
  structure            text,
  cta                  text,
  format_idea          text,
  error                text,
  updated_at           timestamptz not null default now()
);

-- Очередь разбора. Выполняет API (POST /api/radar/jobs/{id}/run), зависшие добирает
-- pg_cron → POST /api/radar/jobs/tick (задание cron ставится отдельно, после деплоя).
create table if not exists public.radar_jobs (
  id               uuid primary key default gen_random_uuid(),
  reel_id          text not null references public.radar_reels(id) on delete cascade,
  mode             text not null check (mode in ('t', 'v', 'tv')),
  state            text not null default 'queued'
                   check (state in ('queued', 'in_progress', 'done', 'failed', 'cancelled')),
  attempts         integer not null default 0,
  next_attempt_at  timestamptz not null default now(),
  error            text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists idx_radar_jobs_state   on public.radar_jobs (state, next_attempt_at);
create index if not exists idx_radar_jobs_reel    on public.radar_jobs (reel_id);
create index if not exists idx_radar_jobs_created on public.radar_jobs (created_at desc);

-- Бэкенд ходит anon-ключом (auth в проекте нет) — открытые политики, как у остальных таблиц.
alter table public.radar_competitors enable row level security;
alter table public.radar_scrape_runs enable row level security;
alter table public.radar_reels       enable row level security;
alter table public.radar_analyses    enable row level security;
alter table public.radar_jobs        enable row level security;

drop policy if exists anon_full_access_radar_competitors on public.radar_competitors;
create policy anon_full_access_radar_competitors on public.radar_competitors
  for all to anon, authenticated using (true) with check (true);

drop policy if exists anon_full_access_radar_scrape_runs on public.radar_scrape_runs;
create policy anon_full_access_radar_scrape_runs on public.radar_scrape_runs
  for all to anon, authenticated using (true) with check (true);

drop policy if exists anon_full_access_radar_reels on public.radar_reels;
create policy anon_full_access_radar_reels on public.radar_reels
  for all to anon, authenticated using (true) with check (true);

drop policy if exists anon_full_access_radar_analyses on public.radar_analyses;
create policy anon_full_access_radar_analyses on public.radar_analyses
  for all to anon, authenticated using (true) with check (true);

drop policy if exists anon_full_access_radar_jobs on public.radar_jobs;
create policy anon_full_access_radar_jobs on public.radar_jobs
  for all to anon, authenticated using (true) with check (true);
