-- ТЗ 10: Разведка Радара. Идемпотентно, как 0008.
alter table public.radar_competitors
  add column if not exists is_source        boolean     not null default false,
  add column if not exists source_added_at  timestamptz,
  add column if not exists excluded_at      timestamptz,
  add column if not exists last_scraped_at  timestamptz,
  add column if not exists full_name        text;
create index if not exists idx_radar_competitors_source
  on public.radar_competitors (is_source) where is_source;

create table if not exists public.radar_refreshes (
  id            bigint generated by default as identity primary key,
  status        text not null default 'running' check (status in ('running','done','error')),
  total_batches integer not null default 0,
  estimate_usd  numeric(10,4),
  cost_usd      numeric(10,4),
  reels_saved   integer not null default 0,
  errors        jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  finished_at   timestamptz
);
create unique index if not exists uq_radar_refresh_one_running
  on public.radar_refreshes ((true)) where status = 'running';

alter table public.radar_scrape_runs
  add column if not exists refresh_id        bigint references public.radar_refreshes(id) on delete set null,
  add column if not exists batch_idx         integer,
  add column if not exists params            jsonb,
  add column if not exists start_claimed_at  timestamptz;
create index if not exists idx_radar_runs_refresh
  on public.radar_scrape_runs (refresh_id, batch_idx);

create table if not exists public.radar_reel_snapshots (
  id            bigint generated by default as identity primary key,
  reel_id       text not null references public.radar_reels(id) on delete cascade,
  views         bigint,
  likes         integer,
  comments      integer,
  taken_at      timestamptz not null default now(),
  scrape_run_id bigint references public.radar_scrape_runs(id) on delete set null
);
create index if not exists idx_radar_snap_reel
  on public.radar_reel_snapshots (reel_id, taken_at desc);
create unique index if not exists uq_radar_snap_run
  on public.radar_reel_snapshots (reel_id, scrape_run_id) where scrape_run_id is not null;

-- Бэкенд ходит anon-ключом (auth в проекте нет) — открытые политики, как в 0008.
alter table public.radar_refreshes       enable row level security;
alter table public.radar_reel_snapshots  enable row level security;

drop policy if exists anon_full_access_radar_refreshes on public.radar_refreshes;
create policy anon_full_access_radar_refreshes on public.radar_refreshes
  for all to anon, authenticated using (true) with check (true);

drop policy if exists anon_full_access_radar_reel_snapshots on public.radar_reel_snapshots;
create policy anon_full_access_radar_reel_snapshots on public.radar_reel_snapshots
  for all to anon, authenticated using (true) with check (true);
